#!/bin/sh
PATH=$PATH:$HOME/scripts
PATH=$PATH:$HOME/scripts/statusbar
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap  -layout us,il -option grp:alt_shift_toggle &
compton --backend glx --vsync opengl-swc --paint-on-overlay --config ~/.config/compton.conf &
feh --bg-scale ~/Pictures/wallpaper.jpg &
~/desktop.sh &
exec dwm
